<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fmumetamodel" nsURI="http://www.eclipse.org/Papyrus/fmu/1.0.0"
    nsPrefix="fmu">
  <eClassifiers xsi:type="ecore:EClass" name="FMUBundle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelDescription" ordered="false"
        eType="ecore:EClass Fmi2ModelDescription.ecore#//FmiModelDescriptionType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourcesFiles" ordered="false"
        upperBound="-1" eType="#//AbstractFile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="win32Files" ordered="false"
        upperBound="-1" eType="#//AbstractFile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="win64Files" ordered="false"
        upperBound="-1" eType="#//AbstractFile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linux32Files" ordered="false"
        upperBound="-1" eType="#//AbstractFile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linux64Files" ordered="false"
        upperBound="-1" eType="#//AbstractFile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="darwin64Files" ordered="false"
        upperBound="-1" eType="#//AbstractFile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="darwin32Files" ordered="false"
        upperBound="-1" eType="#//AbstractFile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="documentationFiles" ordered="false"
        upperBound="-1" eType="#//AbstractFile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceFiles" ordered="false"
        upperBound="-1" eType="#//AbstractFile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootFiles" ordered="false"
        upperBound="-1" eType="#//AbstractFile" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractFile" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="File" instanceClassName="java.io.File">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="File&#xD;&#xA;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FolderToCreateInFMU" eSuperTypes="#//AbstractFile">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" ordered="false"
        upperBound="-1" eType="#//AbstractFile" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchiveToUnzipInFMU" eSuperTypes="#//AbstractFile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="archiveFile" ordered="false"
        lowerBound="1" eType="#//File"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaFileProxy" eSuperTypes="#//AbstractFile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="file" ordered="false" lowerBound="1"
        eType="#//File"/>
  </eClassifiers>
</ecore:EPackage>
