// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fmi.proto

package org.eclipse.papyrus.moka.rcp.protobuff;

public final class Fmi {
  private Fmi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StepRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StepRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional double currentTime = 1;</code>
     */
    double getCurrentTime();

    /**
     * <code>optional double stepSize = 2;</code>
     */
    double getStepSize();

    /**
     * <code>map&lt;int32, double&gt; setRealRequests = 3;</code>
     */
    java.util.Map<java.lang.Integer, java.lang.Double>
    getSetRealRequests();

    /**
     * <code>map&lt;int32, int32&gt; setIntegerRequests = 4;</code>
     */
    java.util.Map<java.lang.Integer, java.lang.Integer>
    getSetIntegerRequests();

    /**
     * <code>map&lt;int32, bool&gt; setBooleanRequests = 5;</code>
     */
    java.util.Map<java.lang.Integer, java.lang.Boolean>
    getSetBooleanRequests();

    /**
     * <code>map&lt;int32, string&gt; setStringRequests = 6;</code>
     */
    java.util.Map<java.lang.Integer, java.lang.String>
    getSetStringRequests();
  }
  /**
   * Protobuf type {@code StepRequest}
   */
  public  static final class StepRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:StepRequest)
      StepRequestOrBuilder {
    // Use StepRequest.newBuilder() to construct.
    private StepRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private StepRequest() {
      currentTime_ = 0D;
      stepSize_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private StepRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 9: {

              currentTime_ = input.readDouble();
              break;
            }
            case 17: {

              stepSize_ = input.readDouble();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                setRealRequests_ = com.google.protobuf.MapField.newMapField(
                    SetRealRequestsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000004;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Double>
              setRealRequests = input.readMessage(
                  SetRealRequestsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              setRealRequests_.getMutableMap().put(setRealRequests.getKey(), setRealRequests.getValue());
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                setIntegerRequests_ = com.google.protobuf.MapField.newMapField(
                    SetIntegerRequestsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000008;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
              setIntegerRequests = input.readMessage(
                  SetIntegerRequestsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              setIntegerRequests_.getMutableMap().put(setIntegerRequests.getKey(), setIntegerRequests.getValue());
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                setBooleanRequests_ = com.google.protobuf.MapField.newMapField(
                    SetBooleanRequestsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000010;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Boolean>
              setBooleanRequests = input.readMessage(
                  SetBooleanRequestsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              setBooleanRequests_.getMutableMap().put(setBooleanRequests.getKey(), setBooleanRequests.getValue());
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                setStringRequests_ = com.google.protobuf.MapField.newMapField(
                    SetStringRequestsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000020;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, java.lang.String>
              setStringRequests = input.readMessage(
                  SetStringRequestsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              setStringRequests_.getMutableMap().put(setStringRequests.getKey(), setStringRequests.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.eclipse.papyrus.moka.rcp.protobuff.Fmi.internal_static_StepRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetSetRealRequests();
        case 4:
          return internalGetSetIntegerRequests();
        case 5:
          return internalGetSetBooleanRequests();
        case 6:
          return internalGetSetStringRequests();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.eclipse.papyrus.moka.rcp.protobuff.Fmi.internal_static_StepRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest.class, org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest.Builder.class);
    }

    private int bitField0_;
    public static final int CURRENTTIME_FIELD_NUMBER = 1;
    private double currentTime_;
    /**
     * <code>optional double currentTime = 1;</code>
     */
    public double getCurrentTime() {
      return currentTime_;
    }

    public static final int STEPSIZE_FIELD_NUMBER = 2;
    private double stepSize_;
    /**
     * <code>optional double stepSize = 2;</code>
     */
    public double getStepSize() {
      return stepSize_;
    }

    public static final int SETREALREQUESTS_FIELD_NUMBER = 3;
    private static final class SetRealRequestsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, java.lang.Double> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, java.lang.Double>newDefaultInstance(
                  org.eclipse.papyrus.moka.rcp.protobuff.Fmi.internal_static_StepRequest_SetRealRequestsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.DOUBLE,
                  0D);
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.Double> setRealRequests_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Double>
    internalGetSetRealRequests() {
      if (setRealRequests_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            SetRealRequestsDefaultEntryHolder.defaultEntry);
     }
      return setRealRequests_;
    }
    /**
     * <code>map&lt;int32, double&gt; setRealRequests = 3;</code>
     */

    public java.util.Map<java.lang.Integer, java.lang.Double> getSetRealRequests() {
      return internalGetSetRealRequests().getMap();
    }

    public static final int SETINTEGERREQUESTS_FIELD_NUMBER = 4;
    private static final class SetIntegerRequestsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, java.lang.Integer> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, java.lang.Integer>newDefaultInstance(
                  org.eclipse.papyrus.moka.rcp.protobuff.Fmi.internal_static_StepRequest_SetIntegerRequestsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0);
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.Integer> setIntegerRequests_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
    internalGetSetIntegerRequests() {
      if (setIntegerRequests_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            SetIntegerRequestsDefaultEntryHolder.defaultEntry);
     }
      return setIntegerRequests_;
    }
    /**
     * <code>map&lt;int32, int32&gt; setIntegerRequests = 4;</code>
     */

    public java.util.Map<java.lang.Integer, java.lang.Integer> getSetIntegerRequests() {
      return internalGetSetIntegerRequests().getMap();
    }

    public static final int SETBOOLEANREQUESTS_FIELD_NUMBER = 5;
    private static final class SetBooleanRequestsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, java.lang.Boolean> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, java.lang.Boolean>newDefaultInstance(
                  org.eclipse.papyrus.moka.rcp.protobuff.Fmi.internal_static_StepRequest_SetBooleanRequestsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.BOOL,
                  false);
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.Boolean> setBooleanRequests_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Boolean>
    internalGetSetBooleanRequests() {
      if (setBooleanRequests_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            SetBooleanRequestsDefaultEntryHolder.defaultEntry);
     }
      return setBooleanRequests_;
    }
    /**
     * <code>map&lt;int32, bool&gt; setBooleanRequests = 5;</code>
     */

    public java.util.Map<java.lang.Integer, java.lang.Boolean> getSetBooleanRequests() {
      return internalGetSetBooleanRequests().getMap();
    }

    public static final int SETSTRINGREQUESTS_FIELD_NUMBER = 6;
    private static final class SetStringRequestsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, java.lang.String>newDefaultInstance(
                  org.eclipse.papyrus.moka.rcp.protobuff.Fmi.internal_static_StepRequest_SetStringRequestsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.String> setStringRequests_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
    internalGetSetStringRequests() {
      if (setStringRequests_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            SetStringRequestsDefaultEntryHolder.defaultEntry);
     }
      return setStringRequests_;
    }
    /**
     * <code>map&lt;int32, string&gt; setStringRequests = 6;</code>
     */

    public java.util.Map<java.lang.Integer, java.lang.String> getSetStringRequests() {
      return internalGetSetStringRequests().getMap();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (currentTime_ != 0D) {
        output.writeDouble(1, currentTime_);
      }
      if (stepSize_ != 0D) {
        output.writeDouble(2, stepSize_);
      }
      for (java.util.Map.Entry<java.lang.Integer, java.lang.Double> entry
           : internalGetSetRealRequests().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Double>
        setRealRequests = SetRealRequestsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(3, setRealRequests);
      }
      for (java.util.Map.Entry<java.lang.Integer, java.lang.Integer> entry
           : internalGetSetIntegerRequests().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
        setIntegerRequests = SetIntegerRequestsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(4, setIntegerRequests);
      }
      for (java.util.Map.Entry<java.lang.Integer, java.lang.Boolean> entry
           : internalGetSetBooleanRequests().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Boolean>
        setBooleanRequests = SetBooleanRequestsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(5, setBooleanRequests);
      }
      for (java.util.Map.Entry<java.lang.Integer, java.lang.String> entry
           : internalGetSetStringRequests().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.String>
        setStringRequests = SetStringRequestsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(6, setStringRequests);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (currentTime_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, currentTime_);
      }
      if (stepSize_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, stepSize_);
      }
      for (java.util.Map.Entry<java.lang.Integer, java.lang.Double> entry
           : internalGetSetRealRequests().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Double>
        setRealRequests = SetRealRequestsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, setRealRequests);
      }
      for (java.util.Map.Entry<java.lang.Integer, java.lang.Integer> entry
           : internalGetSetIntegerRequests().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
        setIntegerRequests = SetIntegerRequestsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, setIntegerRequests);
      }
      for (java.util.Map.Entry<java.lang.Integer, java.lang.Boolean> entry
           : internalGetSetBooleanRequests().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Boolean>
        setBooleanRequests = SetBooleanRequestsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, setBooleanRequests);
      }
      for (java.util.Map.Entry<java.lang.Integer, java.lang.String> entry
           : internalGetSetStringRequests().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.String>
        setStringRequests = SetStringRequestsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(6, setStringRequests);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StepRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StepRequest)
        org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.eclipse.papyrus.moka.rcp.protobuff.Fmi.internal_static_StepRequest_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetSetRealRequests();
          case 4:
            return internalGetSetIntegerRequests();
          case 5:
            return internalGetSetBooleanRequests();
          case 6:
            return internalGetSetStringRequests();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableSetRealRequests();
          case 4:
            return internalGetMutableSetIntegerRequests();
          case 5:
            return internalGetMutableSetBooleanRequests();
          case 6:
            return internalGetMutableSetStringRequests();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.eclipse.papyrus.moka.rcp.protobuff.Fmi.internal_static_StepRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest.class, org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest.Builder.class);
      }

      // Construct using org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        currentTime_ = 0D;

        stepSize_ = 0D;

        internalGetMutableSetRealRequests().clear();
        internalGetMutableSetIntegerRequests().clear();
        internalGetMutableSetBooleanRequests().clear();
        internalGetMutableSetStringRequests().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.eclipse.papyrus.moka.rcp.protobuff.Fmi.internal_static_StepRequest_descriptor;
      }

      public org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest getDefaultInstanceForType() {
        return org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest.getDefaultInstance();
      }

      public org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest build() {
        org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest buildPartial() {
        org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest result = new org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.currentTime_ = currentTime_;
        result.stepSize_ = stepSize_;
        result.setRealRequests_ = internalGetSetRealRequests();
        result.setRealRequests_.makeImmutable();
        result.setIntegerRequests_ = internalGetSetIntegerRequests();
        result.setIntegerRequests_.makeImmutable();
        result.setBooleanRequests_ = internalGetSetBooleanRequests();
        result.setBooleanRequests_.makeImmutable();
        result.setStringRequests_ = internalGetSetStringRequests();
        result.setStringRequests_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest) {
          return mergeFrom((org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest other) {
        if (other == org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest.getDefaultInstance()) return this;
        if (other.getCurrentTime() != 0D) {
          setCurrentTime(other.getCurrentTime());
        }
        if (other.getStepSize() != 0D) {
          setStepSize(other.getStepSize());
        }
        internalGetMutableSetRealRequests().mergeFrom(
            other.internalGetSetRealRequests());
        internalGetMutableSetIntegerRequests().mergeFrom(
            other.internalGetSetIntegerRequests());
        internalGetMutableSetBooleanRequests().mergeFrom(
            other.internalGetSetBooleanRequests());
        internalGetMutableSetStringRequests().mergeFrom(
            other.internalGetSetStringRequests());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private double currentTime_ ;
      /**
       * <code>optional double currentTime = 1;</code>
       */
      public double getCurrentTime() {
        return currentTime_;
      }
      /**
       * <code>optional double currentTime = 1;</code>
       */
      public Builder setCurrentTime(double value) {
        
        currentTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double currentTime = 1;</code>
       */
      public Builder clearCurrentTime() {
        
        currentTime_ = 0D;
        onChanged();
        return this;
      }

      private double stepSize_ ;
      /**
       * <code>optional double stepSize = 2;</code>
       */
      public double getStepSize() {
        return stepSize_;
      }
      /**
       * <code>optional double stepSize = 2;</code>
       */
      public Builder setStepSize(double value) {
        
        stepSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double stepSize = 2;</code>
       */
      public Builder clearStepSize() {
        
        stepSize_ = 0D;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Integer, java.lang.Double> setRealRequests_;
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Double>
      internalGetSetRealRequests() {
        if (setRealRequests_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              SetRealRequestsDefaultEntryHolder.defaultEntry);
       }
        return setRealRequests_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Double>
      internalGetMutableSetRealRequests() {
        onChanged();;
        if (setRealRequests_ == null) {
          setRealRequests_ = com.google.protobuf.MapField.newMapField(
              SetRealRequestsDefaultEntryHolder.defaultEntry);
        }
        if (!setRealRequests_.isMutable()) {
          setRealRequests_ = setRealRequests_.copy();
        }
        return setRealRequests_;
      }
      /**
       * <code>map&lt;int32, double&gt; setRealRequests = 3;</code>
       */
      public java.util.Map<java.lang.Integer, java.lang.Double> getSetRealRequests() {
        return internalGetSetRealRequests().getMap();
      }
      /**
       * <code>map&lt;int32, double&gt; setRealRequests = 3;</code>
       */
      public java.util.Map<java.lang.Integer, java.lang.Double>
      getMutableSetRealRequests() {
        return internalGetMutableSetRealRequests().getMutableMap();
      }
      /**
       * <code>map&lt;int32, double&gt; setRealRequests = 3;</code>
       */
      public Builder putAllSetRealRequests(
          java.util.Map<java.lang.Integer, java.lang.Double> values) {
        getMutableSetRealRequests().putAll(values);
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Integer, java.lang.Integer> setIntegerRequests_;
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
      internalGetSetIntegerRequests() {
        if (setIntegerRequests_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              SetIntegerRequestsDefaultEntryHolder.defaultEntry);
       }
        return setIntegerRequests_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
      internalGetMutableSetIntegerRequests() {
        onChanged();;
        if (setIntegerRequests_ == null) {
          setIntegerRequests_ = com.google.protobuf.MapField.newMapField(
              SetIntegerRequestsDefaultEntryHolder.defaultEntry);
        }
        if (!setIntegerRequests_.isMutable()) {
          setIntegerRequests_ = setIntegerRequests_.copy();
        }
        return setIntegerRequests_;
      }
      /**
       * <code>map&lt;int32, int32&gt; setIntegerRequests = 4;</code>
       */
      public java.util.Map<java.lang.Integer, java.lang.Integer> getSetIntegerRequests() {
        return internalGetSetIntegerRequests().getMap();
      }
      /**
       * <code>map&lt;int32, int32&gt; setIntegerRequests = 4;</code>
       */
      public java.util.Map<java.lang.Integer, java.lang.Integer>
      getMutableSetIntegerRequests() {
        return internalGetMutableSetIntegerRequests().getMutableMap();
      }
      /**
       * <code>map&lt;int32, int32&gt; setIntegerRequests = 4;</code>
       */
      public Builder putAllSetIntegerRequests(
          java.util.Map<java.lang.Integer, java.lang.Integer> values) {
        getMutableSetIntegerRequests().putAll(values);
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Integer, java.lang.Boolean> setBooleanRequests_;
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Boolean>
      internalGetSetBooleanRequests() {
        if (setBooleanRequests_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              SetBooleanRequestsDefaultEntryHolder.defaultEntry);
       }
        return setBooleanRequests_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Boolean>
      internalGetMutableSetBooleanRequests() {
        onChanged();;
        if (setBooleanRequests_ == null) {
          setBooleanRequests_ = com.google.protobuf.MapField.newMapField(
              SetBooleanRequestsDefaultEntryHolder.defaultEntry);
        }
        if (!setBooleanRequests_.isMutable()) {
          setBooleanRequests_ = setBooleanRequests_.copy();
        }
        return setBooleanRequests_;
      }
      /**
       * <code>map&lt;int32, bool&gt; setBooleanRequests = 5;</code>
       */
      public java.util.Map<java.lang.Integer, java.lang.Boolean> getSetBooleanRequests() {
        return internalGetSetBooleanRequests().getMap();
      }
      /**
       * <code>map&lt;int32, bool&gt; setBooleanRequests = 5;</code>
       */
      public java.util.Map<java.lang.Integer, java.lang.Boolean>
      getMutableSetBooleanRequests() {
        return internalGetMutableSetBooleanRequests().getMutableMap();
      }
      /**
       * <code>map&lt;int32, bool&gt; setBooleanRequests = 5;</code>
       */
      public Builder putAllSetBooleanRequests(
          java.util.Map<java.lang.Integer, java.lang.Boolean> values) {
        getMutableSetBooleanRequests().putAll(values);
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Integer, java.lang.String> setStringRequests_;
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
      internalGetSetStringRequests() {
        if (setStringRequests_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              SetStringRequestsDefaultEntryHolder.defaultEntry);
       }
        return setStringRequests_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
      internalGetMutableSetStringRequests() {
        onChanged();;
        if (setStringRequests_ == null) {
          setStringRequests_ = com.google.protobuf.MapField.newMapField(
              SetStringRequestsDefaultEntryHolder.defaultEntry);
        }
        if (!setStringRequests_.isMutable()) {
          setStringRequests_ = setStringRequests_.copy();
        }
        return setStringRequests_;
      }
      /**
       * <code>map&lt;int32, string&gt; setStringRequests = 6;</code>
       */
      public java.util.Map<java.lang.Integer, java.lang.String> getSetStringRequests() {
        return internalGetSetStringRequests().getMap();
      }
      /**
       * <code>map&lt;int32, string&gt; setStringRequests = 6;</code>
       */
      public java.util.Map<java.lang.Integer, java.lang.String>
      getMutableSetStringRequests() {
        return internalGetMutableSetStringRequests().getMutableMap();
      }
      /**
       * <code>map&lt;int32, string&gt; setStringRequests = 6;</code>
       */
      public Builder putAllSetStringRequests(
          java.util.Map<java.lang.Integer, java.lang.String> values) {
        getMutableSetStringRequests().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:StepRequest)
    }

    // @@protoc_insertion_point(class_scope:StepRequest)
    private static final org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest();
    }

    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StepRequest>
        PARSER = new com.google.protobuf.AbstractParser<StepRequest>() {
      public StepRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new StepRequest(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<StepRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StepRequest> getParserForType() {
      return PARSER;
    }

    public org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmptyMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EmptyMessage)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code EmptyMessage}
   */
  public  static final class EmptyMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:EmptyMessage)
      EmptyMessageOrBuilder {
    // Use EmptyMessage.newBuilder() to construct.
    private EmptyMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private EmptyMessage() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private EmptyMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.eclipse.papyrus.moka.rcp.protobuff.Fmi.internal_static_EmptyMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.eclipse.papyrus.moka.rcp.protobuff.Fmi.internal_static_EmptyMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage.class, org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code EmptyMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EmptyMessage)
        org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.eclipse.papyrus.moka.rcp.protobuff.Fmi.internal_static_EmptyMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.eclipse.papyrus.moka.rcp.protobuff.Fmi.internal_static_EmptyMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage.class, org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage.Builder.class);
      }

      // Construct using org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.eclipse.papyrus.moka.rcp.protobuff.Fmi.internal_static_EmptyMessage_descriptor;
      }

      public org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage getDefaultInstanceForType() {
        return org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage.getDefaultInstance();
      }

      public org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage build() {
        org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage buildPartial() {
        org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage result = new org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage) {
          return mergeFrom((org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage other) {
        if (other == org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:EmptyMessage)
    }

    // @@protoc_insertion_point(class_scope:EmptyMessage)
    private static final org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage();
    }

    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EmptyMessage>
        PARSER = new com.google.protobuf.AbstractParser<EmptyMessage>() {
      public EmptyMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new EmptyMessage(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<EmptyMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EmptyMessage> getParserForType() {
      return PARSER;
    }

    public org.eclipse.papyrus.moka.rcp.protobuff.Fmi.EmptyMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StepResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StepResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;int32, double&gt; fmiReals = 1;</code>
     */
    java.util.Map<java.lang.Integer, java.lang.Double>
    getFmiReals();

    /**
     * <code>map&lt;int32, int32&gt; fmiIntegers = 2;</code>
     */
    java.util.Map<java.lang.Integer, java.lang.Integer>
    getFmiIntegers();

    /**
     * <code>map&lt;int32, bool&gt; fmiBooleans = 3;</code>
     */
    java.util.Map<java.lang.Integer, java.lang.Boolean>
    getFmiBooleans();

    /**
     * <code>map&lt;int32, string&gt; fmiStrings = 4;</code>
     */
    java.util.Map<java.lang.Integer, java.lang.String>
    getFmiStrings();
  }
  /**
   * Protobuf type {@code StepResponse}
   */
  public  static final class StepResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:StepResponse)
      StepResponseOrBuilder {
    // Use StepResponse.newBuilder() to construct.
    private StepResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private StepResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private StepResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                fmiReals_ = com.google.protobuf.MapField.newMapField(
                    FmiRealsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Double>
              fmiReals = input.readMessage(
                  FmiRealsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              fmiReals_.getMutableMap().put(fmiReals.getKey(), fmiReals.getValue());
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                fmiIntegers_ = com.google.protobuf.MapField.newMapField(
                    FmiIntegersDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
              fmiIntegers = input.readMessage(
                  FmiIntegersDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              fmiIntegers_.getMutableMap().put(fmiIntegers.getKey(), fmiIntegers.getValue());
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                fmiBooleans_ = com.google.protobuf.MapField.newMapField(
                    FmiBooleansDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000004;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Boolean>
              fmiBooleans = input.readMessage(
                  FmiBooleansDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              fmiBooleans_.getMutableMap().put(fmiBooleans.getKey(), fmiBooleans.getValue());
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                fmiStrings_ = com.google.protobuf.MapField.newMapField(
                    FmiStringsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000008;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, java.lang.String>
              fmiStrings = input.readMessage(
                  FmiStringsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              fmiStrings_.getMutableMap().put(fmiStrings.getKey(), fmiStrings.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.eclipse.papyrus.moka.rcp.protobuff.Fmi.internal_static_StepResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetFmiReals();
        case 2:
          return internalGetFmiIntegers();
        case 3:
          return internalGetFmiBooleans();
        case 4:
          return internalGetFmiStrings();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.eclipse.papyrus.moka.rcp.protobuff.Fmi.internal_static_StepResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse.class, org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse.Builder.class);
    }

    public static final int FMIREALS_FIELD_NUMBER = 1;
    private static final class FmiRealsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, java.lang.Double> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, java.lang.Double>newDefaultInstance(
                  org.eclipse.papyrus.moka.rcp.protobuff.Fmi.internal_static_StepResponse_FmiRealsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.DOUBLE,
                  0D);
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.Double> fmiReals_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Double>
    internalGetFmiReals() {
      if (fmiReals_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            FmiRealsDefaultEntryHolder.defaultEntry);
     }
      return fmiReals_;
    }
    /**
     * <code>map&lt;int32, double&gt; fmiReals = 1;</code>
     */

    public java.util.Map<java.lang.Integer, java.lang.Double> getFmiReals() {
      return internalGetFmiReals().getMap();
    }

    public static final int FMIINTEGERS_FIELD_NUMBER = 2;
    private static final class FmiIntegersDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, java.lang.Integer> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, java.lang.Integer>newDefaultInstance(
                  org.eclipse.papyrus.moka.rcp.protobuff.Fmi.internal_static_StepResponse_FmiIntegersEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0);
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.Integer> fmiIntegers_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
    internalGetFmiIntegers() {
      if (fmiIntegers_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            FmiIntegersDefaultEntryHolder.defaultEntry);
     }
      return fmiIntegers_;
    }
    /**
     * <code>map&lt;int32, int32&gt; fmiIntegers = 2;</code>
     */

    public java.util.Map<java.lang.Integer, java.lang.Integer> getFmiIntegers() {
      return internalGetFmiIntegers().getMap();
    }

    public static final int FMIBOOLEANS_FIELD_NUMBER = 3;
    private static final class FmiBooleansDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, java.lang.Boolean> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, java.lang.Boolean>newDefaultInstance(
                  org.eclipse.papyrus.moka.rcp.protobuff.Fmi.internal_static_StepResponse_FmiBooleansEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.BOOL,
                  false);
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.Boolean> fmiBooleans_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Boolean>
    internalGetFmiBooleans() {
      if (fmiBooleans_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            FmiBooleansDefaultEntryHolder.defaultEntry);
     }
      return fmiBooleans_;
    }
    /**
     * <code>map&lt;int32, bool&gt; fmiBooleans = 3;</code>
     */

    public java.util.Map<java.lang.Integer, java.lang.Boolean> getFmiBooleans() {
      return internalGetFmiBooleans().getMap();
    }

    public static final int FMISTRINGS_FIELD_NUMBER = 4;
    private static final class FmiStringsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, java.lang.String>newDefaultInstance(
                  org.eclipse.papyrus.moka.rcp.protobuff.Fmi.internal_static_StepResponse_FmiStringsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.String> fmiStrings_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
    internalGetFmiStrings() {
      if (fmiStrings_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            FmiStringsDefaultEntryHolder.defaultEntry);
     }
      return fmiStrings_;
    }
    /**
     * <code>map&lt;int32, string&gt; fmiStrings = 4;</code>
     */

    public java.util.Map<java.lang.Integer, java.lang.String> getFmiStrings() {
      return internalGetFmiStrings().getMap();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (java.util.Map.Entry<java.lang.Integer, java.lang.Double> entry
           : internalGetFmiReals().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Double>
        fmiReals = FmiRealsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(1, fmiReals);
      }
      for (java.util.Map.Entry<java.lang.Integer, java.lang.Integer> entry
           : internalGetFmiIntegers().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
        fmiIntegers = FmiIntegersDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(2, fmiIntegers);
      }
      for (java.util.Map.Entry<java.lang.Integer, java.lang.Boolean> entry
           : internalGetFmiBooleans().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Boolean>
        fmiBooleans = FmiBooleansDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(3, fmiBooleans);
      }
      for (java.util.Map.Entry<java.lang.Integer, java.lang.String> entry
           : internalGetFmiStrings().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.String>
        fmiStrings = FmiStringsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(4, fmiStrings);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.Integer, java.lang.Double> entry
           : internalGetFmiReals().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Double>
        fmiReals = FmiRealsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, fmiReals);
      }
      for (java.util.Map.Entry<java.lang.Integer, java.lang.Integer> entry
           : internalGetFmiIntegers().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
        fmiIntegers = FmiIntegersDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, fmiIntegers);
      }
      for (java.util.Map.Entry<java.lang.Integer, java.lang.Boolean> entry
           : internalGetFmiBooleans().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Boolean>
        fmiBooleans = FmiBooleansDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, fmiBooleans);
      }
      for (java.util.Map.Entry<java.lang.Integer, java.lang.String> entry
           : internalGetFmiStrings().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.String>
        fmiStrings = FmiStringsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, fmiStrings);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StepResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StepResponse)
        org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.eclipse.papyrus.moka.rcp.protobuff.Fmi.internal_static_StepResponse_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetFmiReals();
          case 2:
            return internalGetFmiIntegers();
          case 3:
            return internalGetFmiBooleans();
          case 4:
            return internalGetFmiStrings();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableFmiReals();
          case 2:
            return internalGetMutableFmiIntegers();
          case 3:
            return internalGetMutableFmiBooleans();
          case 4:
            return internalGetMutableFmiStrings();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.eclipse.papyrus.moka.rcp.protobuff.Fmi.internal_static_StepResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse.class, org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse.Builder.class);
      }

      // Construct using org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutableFmiReals().clear();
        internalGetMutableFmiIntegers().clear();
        internalGetMutableFmiBooleans().clear();
        internalGetMutableFmiStrings().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.eclipse.papyrus.moka.rcp.protobuff.Fmi.internal_static_StepResponse_descriptor;
      }

      public org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse getDefaultInstanceForType() {
        return org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse.getDefaultInstance();
      }

      public org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse build() {
        org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse buildPartial() {
        org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse result = new org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse(this);
        int from_bitField0_ = bitField0_;
        result.fmiReals_ = internalGetFmiReals();
        result.fmiReals_.makeImmutable();
        result.fmiIntegers_ = internalGetFmiIntegers();
        result.fmiIntegers_.makeImmutable();
        result.fmiBooleans_ = internalGetFmiBooleans();
        result.fmiBooleans_.makeImmutable();
        result.fmiStrings_ = internalGetFmiStrings();
        result.fmiStrings_.makeImmutable();
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse) {
          return mergeFrom((org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse other) {
        if (other == org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse.getDefaultInstance()) return this;
        internalGetMutableFmiReals().mergeFrom(
            other.internalGetFmiReals());
        internalGetMutableFmiIntegers().mergeFrom(
            other.internalGetFmiIntegers());
        internalGetMutableFmiBooleans().mergeFrom(
            other.internalGetFmiBooleans());
        internalGetMutableFmiStrings().mergeFrom(
            other.internalGetFmiStrings());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.Integer, java.lang.Double> fmiReals_;
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Double>
      internalGetFmiReals() {
        if (fmiReals_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              FmiRealsDefaultEntryHolder.defaultEntry);
       }
        return fmiReals_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Double>
      internalGetMutableFmiReals() {
        onChanged();;
        if (fmiReals_ == null) {
          fmiReals_ = com.google.protobuf.MapField.newMapField(
              FmiRealsDefaultEntryHolder.defaultEntry);
        }
        if (!fmiReals_.isMutable()) {
          fmiReals_ = fmiReals_.copy();
        }
        return fmiReals_;
      }
      /**
       * <code>map&lt;int32, double&gt; fmiReals = 1;</code>
       */
      public java.util.Map<java.lang.Integer, java.lang.Double> getFmiReals() {
        return internalGetFmiReals().getMap();
      }
      /**
       * <code>map&lt;int32, double&gt; fmiReals = 1;</code>
       */
      public java.util.Map<java.lang.Integer, java.lang.Double>
      getMutableFmiReals() {
        return internalGetMutableFmiReals().getMutableMap();
      }
      /**
       * <code>map&lt;int32, double&gt; fmiReals = 1;</code>
       */
      public Builder putAllFmiReals(
          java.util.Map<java.lang.Integer, java.lang.Double> values) {
        getMutableFmiReals().putAll(values);
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Integer, java.lang.Integer> fmiIntegers_;
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
      internalGetFmiIntegers() {
        if (fmiIntegers_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              FmiIntegersDefaultEntryHolder.defaultEntry);
       }
        return fmiIntegers_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
      internalGetMutableFmiIntegers() {
        onChanged();;
        if (fmiIntegers_ == null) {
          fmiIntegers_ = com.google.protobuf.MapField.newMapField(
              FmiIntegersDefaultEntryHolder.defaultEntry);
        }
        if (!fmiIntegers_.isMutable()) {
          fmiIntegers_ = fmiIntegers_.copy();
        }
        return fmiIntegers_;
      }
      /**
       * <code>map&lt;int32, int32&gt; fmiIntegers = 2;</code>
       */
      public java.util.Map<java.lang.Integer, java.lang.Integer> getFmiIntegers() {
        return internalGetFmiIntegers().getMap();
      }
      /**
       * <code>map&lt;int32, int32&gt; fmiIntegers = 2;</code>
       */
      public java.util.Map<java.lang.Integer, java.lang.Integer>
      getMutableFmiIntegers() {
        return internalGetMutableFmiIntegers().getMutableMap();
      }
      /**
       * <code>map&lt;int32, int32&gt; fmiIntegers = 2;</code>
       */
      public Builder putAllFmiIntegers(
          java.util.Map<java.lang.Integer, java.lang.Integer> values) {
        getMutableFmiIntegers().putAll(values);
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Integer, java.lang.Boolean> fmiBooleans_;
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Boolean>
      internalGetFmiBooleans() {
        if (fmiBooleans_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              FmiBooleansDefaultEntryHolder.defaultEntry);
       }
        return fmiBooleans_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Boolean>
      internalGetMutableFmiBooleans() {
        onChanged();;
        if (fmiBooleans_ == null) {
          fmiBooleans_ = com.google.protobuf.MapField.newMapField(
              FmiBooleansDefaultEntryHolder.defaultEntry);
        }
        if (!fmiBooleans_.isMutable()) {
          fmiBooleans_ = fmiBooleans_.copy();
        }
        return fmiBooleans_;
      }
      /**
       * <code>map&lt;int32, bool&gt; fmiBooleans = 3;</code>
       */
      public java.util.Map<java.lang.Integer, java.lang.Boolean> getFmiBooleans() {
        return internalGetFmiBooleans().getMap();
      }
      /**
       * <code>map&lt;int32, bool&gt; fmiBooleans = 3;</code>
       */
      public java.util.Map<java.lang.Integer, java.lang.Boolean>
      getMutableFmiBooleans() {
        return internalGetMutableFmiBooleans().getMutableMap();
      }
      /**
       * <code>map&lt;int32, bool&gt; fmiBooleans = 3;</code>
       */
      public Builder putAllFmiBooleans(
          java.util.Map<java.lang.Integer, java.lang.Boolean> values) {
        getMutableFmiBooleans().putAll(values);
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Integer, java.lang.String> fmiStrings_;
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
      internalGetFmiStrings() {
        if (fmiStrings_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              FmiStringsDefaultEntryHolder.defaultEntry);
       }
        return fmiStrings_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
      internalGetMutableFmiStrings() {
        onChanged();;
        if (fmiStrings_ == null) {
          fmiStrings_ = com.google.protobuf.MapField.newMapField(
              FmiStringsDefaultEntryHolder.defaultEntry);
        }
        if (!fmiStrings_.isMutable()) {
          fmiStrings_ = fmiStrings_.copy();
        }
        return fmiStrings_;
      }
      /**
       * <code>map&lt;int32, string&gt; fmiStrings = 4;</code>
       */
      public java.util.Map<java.lang.Integer, java.lang.String> getFmiStrings() {
        return internalGetFmiStrings().getMap();
      }
      /**
       * <code>map&lt;int32, string&gt; fmiStrings = 4;</code>
       */
      public java.util.Map<java.lang.Integer, java.lang.String>
      getMutableFmiStrings() {
        return internalGetMutableFmiStrings().getMutableMap();
      }
      /**
       * <code>map&lt;int32, string&gt; fmiStrings = 4;</code>
       */
      public Builder putAllFmiStrings(
          java.util.Map<java.lang.Integer, java.lang.String> values) {
        getMutableFmiStrings().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:StepResponse)
    }

    // @@protoc_insertion_point(class_scope:StepResponse)
    private static final org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse();
    }

    public static org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StepResponse>
        PARSER = new com.google.protobuf.AbstractParser<StepResponse>() {
      public StepResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new StepResponse(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<StepResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StepResponse> getParserForType() {
      return PARSER;
    }

    public org.eclipse.papyrus.moka.rcp.protobuff.Fmi.StepResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_StepRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_StepRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_StepRequest_SetRealRequestsEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_StepRequest_SetRealRequestsEntry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_StepRequest_SetIntegerRequestsEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_StepRequest_SetIntegerRequestsEntry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_StepRequest_SetBooleanRequestsEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_StepRequest_SetBooleanRequestsEntry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_StepRequest_SetStringRequestsEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_StepRequest_SetStringRequestsEntry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_EmptyMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_EmptyMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_StepResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_StepResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_StepResponse_FmiRealsEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_StepResponse_FmiRealsEntry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_StepResponse_FmiIntegersEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_StepResponse_FmiIntegersEntry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_StepResponse_FmiBooleansEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_StepResponse_FmiBooleansEntry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_StepResponse_FmiStringsEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_StepResponse_FmiStringsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tfmi.proto\"\234\004\n\013StepRequest\022\023\n\013currentTi" +
      "me\030\001 \001(\001\022\020\n\010stepSize\030\002 \001(\001\022:\n\017setRealReq" +
      "uests\030\003 \003(\0132!.StepRequest.SetRealRequest" +
      "sEntry\022@\n\022setIntegerRequests\030\004 \003(\0132$.Ste" +
      "pRequest.SetIntegerRequestsEntry\022@\n\022setB" +
      "ooleanRequests\030\005 \003(\0132$.StepRequest.SetBo" +
      "oleanRequestsEntry\022>\n\021setStringRequests\030" +
      "\006 \003(\0132#.StepRequest.SetStringRequestsEnt" +
      "ry\0326\n\024SetRealRequestsEntry\022\013\n\003key\030\001 \001(\005\022" +
      "\r\n\005value\030\002 \001(\001:\0028\001\0329\n\027SetIntegerRequests",
      "Entry\022\013\n\003key\030\001 \001(\005\022\r\n\005value\030\002 \001(\005:\0028\001\0329\n" +
      "\027SetBooleanRequestsEntry\022\013\n\003key\030\001 \001(\005\022\r\n" +
      "\005value\030\002 \001(\010:\0028\001\0328\n\026SetStringRequestsEnt" +
      "ry\022\013\n\003key\030\001 \001(\005\022\r\n\005value\030\002 \001(\t:\0028\001\"\016\n\014Em" +
      "ptyMessage\"\246\003\n\014StepResponse\022-\n\010fmiReals\030" +
      "\001 \003(\0132\033.StepResponse.FmiRealsEntry\0223\n\013fm" +
      "iIntegers\030\002 \003(\0132\036.StepResponse.FmiIntege" +
      "rsEntry\0223\n\013fmiBooleans\030\003 \003(\0132\036.StepRespo" +
      "nse.FmiBooleansEntry\0221\n\nfmiStrings\030\004 \003(\013" +
      "2\035.StepResponse.FmiStringsEntry\032/\n\rFmiRe",
      "alsEntry\022\013\n\003key\030\001 \001(\005\022\r\n\005value\030\002 \001(\001:\0028\001" +
      "\0322\n\020FmiIntegersEntry\022\013\n\003key\030\001 \001(\005\022\r\n\005val" +
      "ue\030\002 \001(\005:\0028\001\0322\n\020FmiBooleansEntry\022\013\n\003key\030" +
      "\001 \001(\005\022\r\n\005value\030\002 \001(\010:\0028\001\0321\n\017FmiStringsEn" +
      "try\022\013\n\003key\030\001 \001(\005\022\r\n\005value\030\002 \001(\t:\0028\0012\276\001\n\n" +
      "FMIService\022&\n\004init\022\r.EmptyMessage\032\r.Empt" +
      "yMessage\"\000\022\'\n\006doStep\022\014.StepRequest\032\r.Ste" +
      "pResponse\"\000\0222\n\020getInitialValues\022\r.EmptyM" +
      "essage\032\r.StepResponse\"\000\022+\n\tterminate\022\r.E" +
      "mptyMessage\032\r.EmptyMessage\"\000B*\n&org.ecli",
      "pse.papyrus.moka.rcp.protobuffH\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_StepRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_StepRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_StepRequest_descriptor,
        new java.lang.String[] { "CurrentTime", "StepSize", "SetRealRequests", "SetIntegerRequests", "SetBooleanRequests", "SetStringRequests", });
    internal_static_StepRequest_SetRealRequestsEntry_descriptor =
      internal_static_StepRequest_descriptor.getNestedTypes().get(0);
    internal_static_StepRequest_SetRealRequestsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_StepRequest_SetRealRequestsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_StepRequest_SetIntegerRequestsEntry_descriptor =
      internal_static_StepRequest_descriptor.getNestedTypes().get(1);
    internal_static_StepRequest_SetIntegerRequestsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_StepRequest_SetIntegerRequestsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_StepRequest_SetBooleanRequestsEntry_descriptor =
      internal_static_StepRequest_descriptor.getNestedTypes().get(2);
    internal_static_StepRequest_SetBooleanRequestsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_StepRequest_SetBooleanRequestsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_StepRequest_SetStringRequestsEntry_descriptor =
      internal_static_StepRequest_descriptor.getNestedTypes().get(3);
    internal_static_StepRequest_SetStringRequestsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_StepRequest_SetStringRequestsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_EmptyMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EmptyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_EmptyMessage_descriptor,
        new java.lang.String[] { });
    internal_static_StepResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_StepResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_StepResponse_descriptor,
        new java.lang.String[] { "FmiReals", "FmiIntegers", "FmiBooleans", "FmiStrings", });
    internal_static_StepResponse_FmiRealsEntry_descriptor =
      internal_static_StepResponse_descriptor.getNestedTypes().get(0);
    internal_static_StepResponse_FmiRealsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_StepResponse_FmiRealsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_StepResponse_FmiIntegersEntry_descriptor =
      internal_static_StepResponse_descriptor.getNestedTypes().get(1);
    internal_static_StepResponse_FmiIntegersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_StepResponse_FmiIntegersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_StepResponse_FmiBooleansEntry_descriptor =
      internal_static_StepResponse_descriptor.getNestedTypes().get(2);
    internal_static_StepResponse_FmiBooleansEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_StepResponse_FmiBooleansEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_StepResponse_FmiStringsEntry_descriptor =
      internal_static_StepResponse_descriptor.getNestedTypes().get(3);
    internal_static_StepResponse_FmiStringsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_StepResponse_FmiStringsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
