<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fmiprofile" nsURI="http://www.eclipse.org/papyrus/FMIProfile/1.0.0"
    nsPrefix="fmiprofile">
  <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
    <details key="originalName" value="FMIProfile"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="FMU">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fmiVersion" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelName" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="guid" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="copyright" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="license" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generationTool" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generationDateAndTime"
        ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variableNamingConvention"
        ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfEventIndicators"
        ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceFiles" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="canBeInstantiatedOnlyOncePerProcess"
        ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="canGetAndSetFMUstate" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="canNotUseMemoryManagementFunctions"
        ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="canSerializeFMUstate" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="providesDirectionalDerivative"
        ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="needsExecutionTool" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelIdentifier" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelDescription" ordered="false"
        eType="ecore:EClass ../../org.eclipse.papyrus.moka.fmi/model/Fmi2ModelDescription.ecore#//FmiModelDescriptionType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//ScalarVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="ScalarVariable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Property" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variability" ordered="false"
        lowerBound="1" eType="#//VariabilityKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initial" ordered="false"
        lowerBound="1" eType="#//InitialKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueReference" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fmiVariable" ordered="false"
        eType="ecore:EClass ../../org.eclipse.papyrus.moka.fmi/model/Fmi2ModelDescription.ecore#//Fmi2ScalarVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VariabilityKind">
    <eLiterals name="constant"/>
    <eLiterals name="fixed" value="1"/>
    <eLiterals name="tunable" value="2"/>
    <eLiterals name="discrete" value="3"/>
    <eLiterals name="continuous" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InitialKind">
    <eLiterals name="exact"/>
    <eLiterals name="approx" value="1"/>
    <eLiterals name="calculated" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Local" eSuperTypes="#//ScalarVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="CS_FMU" eSuperTypes="#//FMU">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="canHandleVariableCommunicationStepSize"
        ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="canInterpolateInputs" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="canRunAsynchronuously"
        ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxOutputDerivativeOrder"
        ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Real"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stopTime" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Real"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stepSize" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Real"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tolerance" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Real"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ME_FMU" eSuperTypes="#//FMU">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="completedIntegratorStepNotNeeded"
        ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port" eSuperTypes="#//ScalarVariable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Port" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" ordered="false"
        lowerBound="1" eType="#//FlowDirection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FlowDirection">
    <eLiterals name="in"/>
    <eLiterals name="out" value="1"/>
    <eLiterals name="inout" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Independent" eSuperTypes="#//ScalarVariable"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DependenciesKind">
    <eLiterals name="dependent"/>
    <eLiterals name="constant" value="1"/>
    <eLiterals name="fixed" value="2"/>
    <eLiterals name="tunable" value="3"/>
    <eLiterals name="discrete" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Unknown">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Property" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dependencies" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dependenciesKind" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputUnknown" eSuperTypes="#//Unknown"/>
  <eClassifiers xsi:type="ecore:EClass" name="InitialUnknown" eSuperTypes="#//Unknown"/>
  <eClassifiers xsi:type="ecore:EClass" name="DerivativeUnknown" eSuperTypes="#//Unknown"/>
  <eClassifiers xsi:type="ecore:EClass" name="CS_Graph">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Real"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stopTime" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Real"
        defaultValueLiteral="100.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stepSize" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Real"
        defaultValueLiteral="10.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tolerance" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Real"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toleranceDefined" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stopTimeDefined" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="computeSetupExperimentsFromFmus"
        ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DerivativeDependency">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Dependency" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Dependency"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dependencyKind" ordered="false"
        lowerBound="1" eType="#//DependenciesKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputDependency">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Dependency" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Dependency"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitialUnknownDependency">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Dependency" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Dependency"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CalculatedParameter" eSuperTypes="#//ScalarVariable"/>
  <eClassifiers xsi:type="ecore:EEnum" name="CausalityKind">
    <eLiterals name="parameter"/>
    <eLiterals name="calculatedParameter" value="1"/>
    <eLiterals name="input" value="2"/>
    <eLiterals name="output" value="3"/>
    <eLiterals name="local" value="4"/>
    <eLiterals name="independent" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VariabilityNamingConvention">
    <eLiterals name="flat"/>
    <eLiterals name="structured" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BaseUnit">
    <eLiterals name="a"/>
    <eLiterals name="cd" value="1"/>
    <eLiterals name="factor" value="2"/>
    <eLiterals name="k" value="3"/>
    <eLiterals name="kg" value="4"/>
    <eLiterals name="m" value="5"/>
    <eLiterals name="mol" value="6"/>
    <eLiterals name="offset" value="7"/>
    <eLiterals name="rad" value="8"/>
    <eLiterals name="s" value="9"/>
  </eClassifiers>
</ecore:EPackage>
