/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.eclipse.papyrus.moka.fmu.rcp.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Status implements org.apache.thrift.TEnum {
  fmi2OK(0),
  fmi2Warning(1),
  fmi2Discard(2),
  fmi2Error(3),
  fmi2Fatal(4),
  fmi2Pending(5);

  private final int value;

  private Status(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Status findByValue(int value) { 
    switch (value) {
      case 0:
        return fmi2OK;
      case 1:
        return fmi2Warning;
      case 2:
        return fmi2Discard;
      case 3:
        return fmi2Error;
      case 4:
        return fmi2Fatal;
      case 5:
        return fmi2Pending;
      default:
        return null;
    }
  }
}
